### ISSUE TITLE
Latest Code Fixes not in the downloadable release

### ISSUE THREAD

**Issue by ksthomas** [backdrop-contrib/simple_access#8]
I was having an issue with the module not working correctly and in my debugging, fixing on my fork and preparing to perform a pull request, I noticed that the problem has already been fixed. It appears that the links on the backdrop website are not up to date.

**Comment by Graham-72** [comment]
@ksthomas I'm afraid that this module has fallen by the wayside and is not actively maintained. I guess people are using other modules if they have the need.

I have posted an issue about the desirability of making the 'install new modules' process a bit clearer regarding module status. https://github.com/backdrop/backdrop-issues/issues/4224

**Comment by ksthomas** [comment]
@Graham-72 that would be very helpful indeed. Excuse my ignorance before I ask... the code that is released and downloadable doesn't match the code in the main branch of the repo. Is that because its not maintained and the latest fixes have not been tested and released? If so, perhaps I can become the maintainer?

**Comment by Graham-72** [comment]
@ksthomas do you have a particular reason for wanting to use this module rather than another one? The reason I ask is that our project installer system is showing it only has 1 user whereas others have more: Simple Access Grants - 53, Content Access - 28. Maybe one of these would meet your need and be better supported?

Having worked on porting this module I decided it was unnecessarily complicated. The access grants system is hard to understand at the best of times. I therefore produced Simple Access Grants.

Sometimes modules are not actively maintained and as in this case do not have all PRs included in their most recent release. However, they are available for download from the Github repository, though that is a bit more complicated.

If you decide that you want to continue with this module then your volunteering to be maintainer will I am sure be welcomed.

**Comment by ksthomas** [comment]
@Graham-72 The reason for not using the other modules mentioned, they do not support view access mapped to roles at the node level. I use the Simple Access module on all of my D7 installs and have never had any problems with it. Very simple to setup and use. I am migrating most of my D7 sites to BackDrop and like to keep the transition as pain free as possible for the customer. I am open to any module that is as simple and reliable but have not found any.

**Comment by Graham-72** [comment]
@ksthomas Fair enough! Am I to understand that you set an access grant for a role and each individual node and not just for a role and a node type as done in Simple Access Grants? 

Have you found whether this release of a Backdrop version of Simple Access, subject to the outstanding PRs, will work as you need, or are there likely to be more issues? As I do not use it I have not the time or the personal inclination to take on the responsibility for testing and maintaining the module but I could make a new release with what we have now, then leave it for someone else to become maintainer. But I wouldn't want to do this if there are other current issues that need attention.

If you are able to become maintainer that would be great.

**Comment by ksthomas** [comment]
@Graham-72  I am testing the module before I respond. I will let you know. Thank you!

**Comment by Graham-72** [comment]
@ksthomas thank you. I look forward to hearing how you get on.

**Comment by stpaultim** [comment]
I'm going to close this issue. There have been new releases since the last comment in this ticket.
